services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: ./backend
    container_name: nest-api
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "9001:9001"
    depends_on:
      - db

  web:
    build:
      context: ./frontend
    container_name: react-frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  postgres-data: